/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:722d436c-b050-4ca7-84ee-6f22f02fc463",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_dqzUaOZrG",
    "aws_user_pools_web_client_id": "7bjadrmc8vqpi7b2smque4n7js",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://v7vcyxmyt5be7n7bi6zwcdybyu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "2678f33c848f453b9027d1e7b1ff6197",
    "aws_mobile_analytics_app_region": "eu-west-1"
};


export default awsmobile;
