/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:9f16a46b-62a1-4284-8183-375a3e3f0bc3",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_hkIYCd7OM",
    "aws_user_pools_web_client_id": "47djbfg1np1e8p0ug50r8n9m6t",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://mftperxncvhordrvmzo2pw4fcu.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "924cdf4c781d4e779ce657ab61117934",
    "aws_mobile_analytics_app_region": "eu-west-2"
};


export default awsmobile;
